stages:
  - test-submodule
  - trigger-mentor-plugins

include:
  - component: $CI_SERVER_FQDN/devops/cicd/gitlab-ci-toolkit/mentor-submodule-test@mentor
    inputs:
      submodule_branch: $CI_COMMIT_REF_NAME
      submodule_path: "theme/mentor"
      submodule_testsuite: "mentor_theme_testsuite"
  - component: $CI_SERVER_FQDN/devops/cicd/gitlab-ci-toolkit/mentor-submodules-deploy@mentor